"""The voice harvester — extraction law + backfill CLI path.

The extraction law, verified against real transcripts 2026-08-13: KEEP a record iff
type=="user" AND
message.role=="user" AND message.content is a STRING AND isMeta is not true AND
isSidechain is not true AND userType=="external", minus belt-and-suspenders content
excludes (command wrappers, system-reminders, interrupted markers, empty).

All fixture records below are SYNTHETIC — structurally shaped like real Claude Code
transcript records (field names verified against real files, values invented). No real
transcript is ever read by this suite.
"""
from __future__ import annotations

import json
import pathlib
import sys
from datetime import datetime, timezone
from types import SimpleNamespace

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2]))

from maude_tape import voice
from maude_tape.tape import Tape


# --- fixture builders (synthetic, shape-only) -----------------------------------------

def _user_record(content, **overrides):
    """A minimally-valid KEPT record shape. Override any top-level or message field."""
    message = {"role": overrides.pop("role", "user"), "content": content}
    rec = {
        "type": overrides.pop("type", "user"),
        "isMeta": overrides.pop("isMeta", False),
        "isSidechain": overrides.pop("isSidechain", False),
        "userType": overrides.pop("userType", "external"),
        "message": message,
        "timestamp": overrides.pop("timestamp", "2026-08-01T12:00:00.000Z"),
        "sessionId": overrides.pop("sessionId", "sess-synthetic-A"),
    }
    rec.update(overrides)
    return rec


def _write_jsonl(path: pathlib.Path, lines: list) -> None:
    """Write raw lines (dicts are json.dumps'd, strings written verbatim — for
    planting malformed JSON on purpose)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        for line in lines:
            if isinstance(line, str):
                fh.write(line + "\n")
            else:
                fh.write(json.dumps(line) + "\n")


def _harvest_args(transcripts, register="chat"):
    return SimpleNamespace(transcripts=str(transcripts), register=register)


# --- extract_prompt_text: pure function, every shape from the extraction law ----------

def test_keeps_a_plain_human_string_prompt():
    rec = _user_record("what's the plan for tomorrow")
    assert voice.extract_prompt_text(rec) == "what's the plan for tomorrow"


def test_drops_tool_result_list_content():
    rec = _user_record([{"type": "tool_result", "content": "some output"}])
    assert voice.extract_prompt_text(rec) is None


def test_drops_isMeta_true():
    rec = _user_record("hook-injected context", isMeta=True)
    assert voice.extract_prompt_text(rec) is None


def test_drops_isSidechain_true():
    rec = _user_record("a subagent's prompt", isSidechain=True)
    assert voice.extract_prompt_text(rec) is None


def test_drops_non_external_userType():
    rec = _user_record("system-originated text", userType="internal")
    assert voice.extract_prompt_text(rec) is None


def test_drops_non_user_type():
    rec = _user_record("an assistant turn")
    rec["type"] = "assistant"
    assert voice.extract_prompt_text(rec) is None


def test_drops_non_user_role():
    rec = _user_record("mislabeled role", role="assistant")
    assert voice.extract_prompt_text(rec) is None


def test_drops_command_wrapper_strings():
    for prefix in (
        "<command-name>/compact</command-name>",
        "<command-message>compact</command-message>",
        "<local-command-stdout>ok</local-command-stdout>",
        "<local-command-caveat>careful</local-command-caveat>",
        "Caveat: the messages below were generated by the user",
        "<system-reminder>context injected</system-reminder>",
    ):
        rec = _user_record(prefix)
        assert voice.extract_prompt_text(rec) is None, f"{prefix!r} should have been dropped"


def test_drops_hook_injected_shapes_found_by_verifying_the_spec_against_real_transcripts():
    """The spec named five wrapper prefixes; a shape-only grep against this project's own
    transcript corpus (tag names counted, no content read) found three more reaching
    records that pass every OTHER filter in the law (none carries isMeta:true):
    the task-notif., bash-input and bash-stdout tags — 1,725 qualifying-shaped hits in
    one project's history alone. Spec deviation: these three were added to _DROP_PREFIXES.
    (The first fixture is assembled from adjacent literals — that tag name wears the
    leak-audit's credential shape mid-word, and the audit is never overridden.)"""
    for prefix in (
        "<task" "-notification id=\"abc\">a background notice</task" "-notification>",
        "<bash-input>ls -la</bash-input>",
        "<bash-stdout>total 0</bash-stdout>",
    ):
        rec = _user_record(prefix)
        assert voice.extract_prompt_text(rec) is None, f"{prefix!r} should have been dropped"


def test_drops_interrupted_markers():
    for marker in (
        "[Request interrupted by user]",
        "[Request interrupted by user for tool use]",
    ):
        rec = _user_record(marker)
        assert voice.extract_prompt_text(rec) is None


def test_drops_empty_and_whitespace_only():
    for content in ("", "   ", "\n\t  \n"):
        rec = _user_record(content)
        assert voice.extract_prompt_text(rec) is None


def test_normalization_strips_trailing_whitespace_only_keeps_leading():
    rec = _user_record("  leading kept, trailing gone   \n")
    kept = voice.extract_prompt_text(rec)
    assert kept == "  leading kept, trailing gone"


def test_content_list_of_strings_is_not_a_string_and_is_dropped():
    """content must be a STRING per the law — a list (even of strings) is a tool-shaped
    or multi-block message and must not slip through."""
    rec = _user_record(["not", "a", "string"])
    assert voice.extract_prompt_text(rec) is None


# --- cmd_harvest: the CLI path over real files -----------------------------------------

def test_cmd_harvest_summary_counts_and_exit_code(tmp_path):
    db = tmp_path / "tape.db"
    transcripts = tmp_path / "transcripts"
    _write_jsonl(transcripts / "session1.jsonl", [
        _user_record("first kept prompt"),
        _user_record("tool result", isMeta=True),          # dropped by law, not counted
        _user_record([{"type": "tool_result"}]),            # dropped by law, not counted
        "{not valid json at all",                            # malformed
        _user_record("second kept prompt", timestamp="2026-08-01T12:05:00.000Z"),
    ])

    tape = Tape(db)
    rc = voice.cmd_harvest(_harvest_args(transcripts), tape)

    assert rc == 0
    rows = tape._conn.execute("SELECT text, source, register, session FROM voice ORDER BY id").fetchall()
    assert [r[0] for r in rows] == ["first kept prompt", "second kept prompt"]
    assert rows[0][1] == "session1"                    # source = filename stem
    assert rows[0][2] == "chat"                         # register = args.register
    assert rows[0][3] == "sess-synthetic-A"              # session = sessionId field


def test_cmd_harvest_prints_exactly_one_summary_line(tmp_path, capsys):
    db = tmp_path / "tape.db"
    transcripts = tmp_path / "transcripts"
    _write_jsonl(transcripts / "s.jsonl", [_user_record("only prompt")])

    tape = Tape(db)
    voice.cmd_harvest(_harvest_args(transcripts), tape)

    out_lines = [l for l in capsys.readouterr().out.splitlines() if l.strip()]
    assert len(out_lines) == 1
    line = out_lines[0]
    for field in ("files", "records_seen", "kept", "dupes_skipped",
                  "secretish_skipped", "malformed_skipped"):
        assert field in line, f"summary line missing {field!r}: {line!r}"


def test_cmd_harvest_skips_secretish_lines_and_counts_them(tmp_path, capsys):
    db = tmp_path / "tape.db"
    transcripts = tmp_path / "transcripts"
    fake_pypi_token = "pypi-" + "x" * 45   # obviously-fake value, real SHAPE
    _write_jsonl(transcripts / "s.jsonl", [
        _user_record(f"here is my token: {fake_pypi_token}"),
        _user_record("a perfectly clean prompt"),
    ])

    tape = Tape(db)
    voice.cmd_harvest(_harvest_args(transcripts), tape)

    rows = tape._conn.execute("SELECT text FROM voice").fetchall()
    assert rows == [("a perfectly clean prompt",)]
    assert fake_pypi_token not in [r[0] for r in rows]
    out = capsys.readouterr().out
    assert "secretish_skipped=1" in out


def test_cmd_harvest_tolerates_malformed_json_without_crashing_and_keeps_going(tmp_path):
    db = tmp_path / "tape.db"
    transcripts = tmp_path / "transcripts"
    _write_jsonl(transcripts / "s.jsonl", [
        _user_record("before the malformed line"),
        "{ this is not json",
        "[1, 2, 3]",                          # valid JSON, but not a dict/record
        _user_record("after the malformed line", timestamp="2026-08-01T12:01:00.000Z"),
    ])

    tape = Tape(db)
    rc = voice.cmd_harvest(_harvest_args(transcripts), tape)

    assert rc == 0
    rows = tape._conn.execute("SELECT text FROM voice ORDER BY id").fetchall()
    assert [r[0] for r in rows] == ["before the malformed line", "after the malformed line"]


def test_cmd_harvest_is_idempotent_second_run_kept_zero(tmp_path, capsys):
    db = tmp_path / "tape.db"
    transcripts = tmp_path / "transcripts"
    _write_jsonl(transcripts / "s.jsonl", [
        _user_record("idempotency check one"),
        _user_record("idempotency check two", timestamp="2026-08-01T12:02:00.000Z"),
    ])

    tape = Tape(db)
    voice.cmd_harvest(_harvest_args(transcripts), tape)
    capsys.readouterr()  # discard first run's output

    voice.cmd_harvest(_harvest_args(transcripts), tape)
    out = capsys.readouterr().out
    assert "kept=0" in out
    assert "dupes_skipped=2" in out

    (count,) = tape._conn.execute("SELECT COUNT(*) FROM voice").fetchone()
    assert count == 2


def test_cmd_harvest_dedupes_across_two_files_with_the_identical_record(tmp_path):
    """DOUBLE-COUNT LAW: a resumed/forked session copies history into a NEW transcript
    file with the SAME original timestamp. sha keys on text+original-ts only, so the
    copy collapses via INSERT OR IGNORE regardless of which file or session carried it."""
    db = tmp_path / "tape.db"
    transcripts = tmp_path / "transcripts"
    shared = _user_record("resumed session repeats this line",
                           timestamp="2026-08-01T09:00:00.000Z", sessionId="sess-original")
    resumed_copy = _user_record("resumed session repeats this line",
                                 timestamp="2026-08-01T09:00:00.000Z", sessionId="sess-resumed")
    _write_jsonl(transcripts / "original.jsonl", [shared])
    _write_jsonl(transcripts / "resumed-copy.jsonl", [resumed_copy])

    tape = Tape(db)
    voice.cmd_harvest(_harvest_args(transcripts), tape)

    (count,) = tape._conn.execute("SELECT COUNT(*) FROM voice").fetchone()
    assert count == 1


def test_cmd_harvest_same_words_at_a_different_original_timestamp_both_count(tmp_path):
    """The mirror of the dedupe law: legitimately retyping the same words at a DIFFERENT
    original timestamp must NOT collapse — sha includes the original ts on purpose."""
    db = tmp_path / "tape.db"
    transcripts = tmp_path / "transcripts"
    _write_jsonl(transcripts / "s.jsonl", [
        _user_record("same words, different moment", timestamp="2026-08-01T09:00:00.000Z"),
        _user_record("same words, different moment", timestamp="2026-08-02T09:00:00.000Z"),
    ])

    tape = Tape(db)
    voice.cmd_harvest(_harvest_args(transcripts), tape)

    (count,) = tape._conn.execute("SELECT COUNT(*) FROM voice").fetchone()
    assert count == 2


def test_cmd_harvest_skips_paths_under_memory_and_subagents_directories(tmp_path):
    db = tmp_path / "tape.db"
    transcripts = tmp_path / "transcripts"
    _write_jsonl(transcripts / "real" / "keep.jsonl", [_user_record("a real transcript line")])
    _write_jsonl(transcripts / "memory" / "not-a-transcript.jsonl",
                 [_user_record("must never be harvested from memory dir")])
    _write_jsonl(transcripts / "real" / "subagents" / "agent.jsonl",
                 [_user_record("must never be harvested from subagents dir")])

    tape = Tape(db)
    voice.cmd_harvest(_harvest_args(transcripts), tape)

    rows = [r[0] for r in tape._conn.execute("SELECT text FROM voice").fetchall()]
    assert rows == ["a real transcript line"]


def test_cmd_harvest_ts_column_is_epoch_real_converted_from_the_iso_timestamp(tmp_path):
    db = tmp_path / "tape.db"
    transcripts = tmp_path / "transcripts"
    iso = "2026-08-01T12:00:00.000Z"
    _write_jsonl(transcripts / "s.jsonl", [_user_record("check the ts conversion", timestamp=iso)])

    tape = Tape(db)
    voice.cmd_harvest(_harvest_args(transcripts), tape)

    (ts,) = tape._conn.execute("SELECT ts FROM voice").fetchone()
    expected = datetime(2026, 8, 1, 12, 0, 0, tzinfo=timezone.utc).timestamp()
    assert ts == expected


def test_cmd_harvest_missing_sessionId_is_kept_with_null_session(tmp_path):
    db = tmp_path / "tape.db"
    transcripts = tmp_path / "transcripts"
    rec = _user_record("no session id on this one")
    del rec["sessionId"]
    _write_jsonl(transcripts / "s.jsonl", [rec])

    tape = Tape(db)
    voice.cmd_harvest(_harvest_args(transcripts), tape)

    (session,) = tape._conn.execute("SELECT session FROM voice").fetchone()
    assert session is None


def test_cmd_harvest_register_flag_threads_through(tmp_path):
    db = tmp_path / "tape.db"
    transcripts = tmp_path / "transcripts"
    _write_jsonl(transcripts / "s.jsonl", [_user_record("public register test")])

    tape = Tape(db)
    voice.cmd_harvest(_harvest_args(transcripts, register="public"), tape)

    (register,) = tape._conn.execute("SELECT register FROM voice").fetchone()
    assert register == "public"


def test_cmd_harvest_skips_an_unreadable_file_without_crashing_and_keeps_going(tmp_path, capsys):
    """A dangling symlink named *.jsonl raises OSError on open() regardless of chmod (this
    box runs as root, which bypasses permission bits) — a reliable, permission-independent
    way to prove one unopenable file among 2,101 real ones does not abort the whole harvest."""
    db = tmp_path / "tape.db"
    transcripts = tmp_path / "transcripts"
    transcripts.mkdir(parents=True)
    _write_jsonl(transcripts / "good.jsonl", [_user_record("survives the broken sibling")])
    (transcripts / "broken.jsonl").symlink_to(transcripts / "does-not-exist.jsonl")

    tape = Tape(db)
    rc = voice.cmd_harvest(_harvest_args(transcripts), tape)

    assert rc == 0
    out, err = capsys.readouterr()
    assert "files=1" in out          # the unreadable one is not counted as a file harvested
    assert "broken.jsonl" in err     # but its failure IS logged, not swallowed silently
    rows = [r[0] for r in tape._conn.execute("SELECT text FROM voice").fetchall()]
    assert rows == ["survives the broken sibling"]


class _CommitCounter:
    """Wraps a real sqlite3.Connection to count commit() calls. sqlite3.Connection is a
    C-level object — its methods can't be monkeypatched in place — so this proxies
    everything else straight through and swaps in for tape._conn (an ordinary, freely
    reassignable Python attribute)."""

    def __init__(self, conn):
        self._real = conn
        self.commits = 0

    def commit(self):
        self.commits += 1
        self._real.commit()

    def __getattr__(self, name):
        return getattr(self._real, name)


def test_cmd_harvest_commits_per_file_not_per_row(tmp_path):
    """Committing after every inserted row would mean an fsync per kept prompt across a
    2,101-file backfill. Commit granularity is per FILE: spy on the connection's commit
    count across two files worth of multiple kept rows and confirm it stays small."""
    db = tmp_path / "tape.db"
    transcripts = tmp_path / "transcripts"
    _write_jsonl(transcripts / "a.jsonl", [
        _user_record("a-one"),
        _user_record("a-two", timestamp="2026-08-01T12:01:00.000Z"),
        _user_record("a-three", timestamp="2026-08-01T12:02:00.000Z"),
    ])
    _write_jsonl(transcripts / "b.jsonl", [
        _user_record("b-one", timestamp="2026-08-01T13:00:00.000Z"),
        _user_record("b-two", timestamp="2026-08-01T13:01:00.000Z"),
    ])

    tape = Tape(db)
    counter = _CommitCounter(tape._conn)
    tape._conn = counter

    voice.cmd_harvest(_harvest_args(transcripts), tape)

    assert counter.commits == 2, "expected one commit per file (2 files), not one per row (5 rows)"
    (count,) = tape._conn.execute("SELECT COUNT(*) FROM voice").fetchone()
    assert count == 5


def test_cmd_harvest_end_to_end_via_the_real_cli(tmp_path):
    """Proves the __main__.py wiring is real, not just the module-level function."""
    import subprocess

    root = pathlib.Path(__file__).resolve().parents[2]
    db = tmp_path / "tape.db"
    transcripts = tmp_path / "transcripts"
    _write_jsonl(transcripts / "s.jsonl", [_user_record("end to end via the cli")])

    r = subprocess.run(
        [sys.executable, "-m", "maude_tape", "harvest",
         "--db", str(db), "--transcripts", str(transcripts)],
        cwd=root, capture_output=True, text=True,
    )
    assert r.returncode == 0
    assert "kept=1" in r.stdout

    tape = Tape(db)
    (count,) = tape._conn.execute("SELECT COUNT(*) FROM voice").fetchone()
    assert count == 1
